### ISSUE TITLE
【質問】TVTestからのチャンネルスキャンについて

### ISSUE THREAD

**Issue by cuckoozero** [Chinachu/BonDriver_Mirakurun#11]
Win10 home x64で 
PT3 → BonDriver_PT3-ST → BonRecTest → Mirakurun → BonDriver_mirakurun → TVTest
の環境にチャレンジしているのですが、TVTestでBSのチャンネルスキャンをすると以下のように選局不能なチャンネルが混ざった形でスキャンされます。

; TVTest チャンネル設定ファイル
; 名称,チューニング空間,チャンネル,リモコン番号,サービスタイプ,サービスID,ネットワークID,TSID,状態
;#SPACE(1,BS) 
ＮＨＫＢＳ１,1,0,1,1,101,4,16625,1 
ＮＨＫＢＳ１,1,1,1,1,101,4,16625,1 
ＮＨＫＢＳ１,1,45,1,1,101,4,16625,0 
ＮＨＫＢＳ１,1,46,1,1,101,4,16625,0 
ＮＨＫＢＳ１,1,58,1,1,101,4,16625,0 
ＮＨＫＢＳ１,1,0,2,1,102,4,16625,0 
ＮＨＫＢＳ１,1,1,2,1,102,4,16625,0 
ＮＨＫＢＳ１,1,45,2,1,102,4,16625,,0 
ＮＨＫＢＳ１,1,58,2,1,102,4,16625,0 

ちなみに
PT3 → BonDriver_PT3-ST → TVTest
という構成にした場合は以下のようにスキャンされます。

;#SPACE(0,BS)
ＮＨＫＢＳ１,0,17,1,1,101,4,16625,1
ＮＨＫＢＳ１,0,17,2,1,102,4,16625,0

これについて何か解決法があれば教えて頂けると助かります。

**Comment by cuckoozero** [comment]
原因がわかりました。
BonDriver_Mirakurun.iniでSERVICE_SPLIT=1を設定すると正常にスキャンされないようです。
SERVICE_SPLIT=0にすると正常にスキャンできます。
しかしその後、SERVICE_SPLIT=1に戻すと、選局が正常にできなくなります。
TVTest側の問題かもしれませんが、ご報告まで。

**Comment by m10i1986** [comment]
情報ありがとうございました

**Comment by sigegyan** [comment]
TVTest ３日間Tryしているが　いまだ視聴できない。チャンネルスキャン最後の１歩で落ちる。探し抜いたが解決策無し。

**Comment by m10i1986** [comment]
新規issueを立てました
以後はそちらでお願いいたします
