### ISSUE TITLE
【要望】MirakurunからBonDriver_Mirakurunへの送信をチャンネルごとではなくサービスごとに（ネットワーク帯域削減のため）

### ISSUE THREAD

**Issue by tkmsst** [Chinachu/BonDriver_Mirakurun#3]
LinuxでMirakurunを導入し、Windows側でBonDriver_Mirakurunを使って視聴する場合、現在はワンセグも含めて、チャンネル内のすべてのサービスが送信されるようになっています。そのため、特にCSを視聴する場合にネットワークの帯域が圧迫されてしまいます。

そこで下のリンクのような要領で、
https://github.com/u-n-k-n-o-w-n/BonDriverProxy_Linux/blob/master/BonDriver_Splitter.conf
Mirakurunの方であらかじめ1チャンネル1サービスにスプリットしてから（この際に不要なPSI/SIを削除できるとなお良い）BonDriver_Mirakurunに送信できるようにしていただけると大変ありがたいです。

スプリットする/しない、削除するPSI/SIについてはBonDriver_Mirakurun.iniで指定できると良いと思いますが、Mirakurunのserver.ymlでもいいかもしれません。

ご考慮いただけましたら幸いです。

**Comment by tkmsst** [comment]
どちらかというとMirakurunの方に書く内容でしたので一旦Close致します。

**Comment by akimasa** [comment]
https://github.com/akimasa/BonDriver_Mirakurun/releases/tag/v1.2.2-alpha
それっぽいのを作ってみました。

追記：
リンク先のバイナリは大丈夫なはずです。が、ソースが違うコミットのリンクを一時期貼ってしまいました。今はソースも大丈夫なはずです。

**Comment by tkmsst** [comment]
akimasaさん、ありがとうございます。参考にさせて頂き、チューナ空間ごとに表示されるようにして下記にcommitしました。
https://github.com/epgdatacapbon/BonDriver_Mirakurun/tree/service

あとはBonDriver_Splitterのように、不要なPSI/SIを削除してから送信できるようになれば完成かと思います。（Mirakurun側の対応が必要でしょうか）

**Comment by akimasa** [comment]
https://github.com/akimasa/Mirakurun/tree/delpids-dev
https://github.com/akimasa/BonDriver_Mirakurun/tree/del-pids

不要なPIDを送信しない設定をつけてみました。
上記のURLにあるMirakurunとBonDriver_Mirakurunを使い、BonDriver_Mirakurunの設定ではSERVICE_SPLIT=1かつDELETE_PIDSがコメントアウトされていない時だけちゃんと指定されたPIDが消されます。

**Comment by m10i1986** [comment]
有難う御座います
先ほどマージしました
特に問題が無ければこちらのIssuesもCloseしたいと考えております
